# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      # skipping breakpoints
      # shouldn't we just have one breakpoint mixin with a param?
      exclude:
        - bp-1
        - bp-2
        - bp-3
        - bp-4
        - bp-5
        - bp-6

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 2
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order: 0
  variable-for-property: 0
  quotes:
    - 2
    -
      style: double

  nesting-depth:
    - 1
    -
      max-depth: 4

  space-after-comma: 2
  space-after-colon: 2
  single-line-per-selector: 2
  empty-line-between-blocks: 2

  no-color-literals: 0

  # We'd probably like this one but too big a jump now
  space-around-operator: 0
  # mixins-before-declarations: 0

  # These ones seem to get too many false positives
  force-element-nesting: 0
  variable-name-format: 0
  no-mergeable-selectors: 0
  force-pseudo-nesting: 0
  no-duplicate-properties: 0
